export enum ECurrencySymbol {
  USD = '$', // Dólar estadounidense
  PEN = 'S/.', // Sol peruano
  CLP = '$', // Peso chileno
  COP = '$', // Peso colombiano
  BRL = 'R$', // Real brasileño
  ARS = '$', // Peso argentino
  MXN = '$', // Peso mexicano
  CAD = '$', // Dólar canadiense
  UYU = '$', // Peso uruguayo
  VES = 'Bs.', // Bolívar soberano venezolano
  GTQ = 'Q', // Quetzal guatemalteco
  HNL = 'L', // Lempira hondureño
  NIO = 'C$', // Córdoba nicaragüense
  DOP = 'RD$', // Peso dominicano
  PAB = 'B/.', // Balboa panameño
  BSD = '$', // Dólar bahameño
  BBD = '$', // Dólar barbadense
  BZD = 'BZ$', // Dólar beliceño
  XCD = '$', // Dólar del Caribe Oriental
  HTG = 'G', // Gourde haitiano
  JMD = 'J$', // Dólar jamaicano
  EUR = '€', // Euro
  GBP = '£', // Libra esterlina
  CHF = 'CHF', // Franco suizo
  SEK = 'kr', // Corona sueca
  NOK = 'kr', // Corona noruega
  DKK = 'kr'  // Corona danesa
}
